In [1]:
from test import *


In [2]:
model, training_losses, training_accuracies, validation_accuracies = train_multi_model(train_data=training_set, test_data=test_set, model=MLP,
                        optim="SAM", batch_size=100, epochs=5, tracking=True)
                        

  0%|          | 0/5 [00:00<?, ?it/s]

In [3]:
print(f"SAM training accuracies: {training_accuracies}")
print(f"SAM validation accuracies: {validation_accuracies}")

SAM training accuracies: [0.7462999820709229, 0.9121666550636292, 0.9282833337783813, 0.9371833205223083, 0.9430333375930786]
SAM validation accuracies: [0.8942999839782715, 0.9240999817848206, 0.9336000084877014, 0.9412999749183655, 0.944100022315979]


In [1]:
# be careful with comparisons, you have to restart the kernel every time to initialize a new model
from test import *

In [2]:
model, training_losses, training_accuracies, validation_accuracies = train_multi_model(train_data=training_set, test_data=test_set, model=MLP,
                        optim="MegaSAM", batch_size=100, epochs=5, tracking=True)

[{'params': [Parameter containing:
tensor([[-0.0326,  0.0247, -0.0240,  ...,  0.0263, -0.0255, -0.0348],
        [-0.0037, -0.0233, -0.0332,  ...,  0.0282, -0.0347,  0.0150],
        [ 0.0293,  0.0071,  0.0080,  ...,  0.0282, -0.0258,  0.0313],
        ...,
        [-0.0093,  0.0116, -0.0117,  ...,  0.0035,  0.0257, -0.0237],
        [ 0.0019, -0.0017, -0.0054,  ..., -0.0072,  0.0292, -0.0186],
        [-0.0094, -0.0353,  0.0026,  ..., -0.0324,  0.0118, -0.0303]],
       requires_grad=True), Parameter containing:
tensor([-0.0053,  0.0280,  0.0174,  0.0120,  0.0115,  0.0268,  0.0210,  0.0332,
         0.0336, -0.0168,  0.0006, -0.0105, -0.0267,  0.0308, -0.0340,  0.0195],
       requires_grad=True), Parameter containing:
tensor([[-0.2492,  0.1713,  0.1409,  0.0476, -0.1988, -0.1748,  0.1371,  0.0762,
         -0.0735, -0.1610,  0.2276,  0.1399,  0.0940,  0.2233,  0.0643,  0.0749],
        [-0.0479,  0.2381, -0.2102,  0.0039, -0.1811, -0.1103, -0.2474, -0.0210,
          0.2001, -0.1473,

  0%|          | 0/5 [00:00<?, ?it/s]

c:\Users\szilv\OneDrive\Dokumentumok\summer_2022\Summer-2022\MegaAdaptiveSAM\MegaSAM\mega_adaptive_sam.py:96: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2985.)
  norm = torch.sqrt(M_inv.T @ grads_flattened**2)


In [3]:
print(f"SAM training accuracies: {training_accuracies}")
print(f"SAM validation accuracies: {validation_accuracies}")

SAM training accuracies: [0.2921999990940094, 0.625166654586792, 0.7925000190734863, 0.8503000140190125, 0.8730166554450989]
SAM validation accuracies: [0.4146000146865845, 0.7408000230789185, 0.8327000141143799, 0.8623999953269958, 0.8784000277519226]
