In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from tqdm.notebook import tqdm, trange
# from sklearn import datasets
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
device = "cuda" if torch.cuda.is_available() else "cpu"
from sam.sam import SAM

from mega_sam_feri import MegaSAM
from NN_utils import train_multi_model
from data.mnist import mnist_data_gen

#import sys; sys.path.append("..")
#sys.path.append("sam")


In [2]:
training_set, test_set= mnist_data_gen()

training_set = [(i[0].flatten(), i[1]) for i in training_set]
test_set = [(i[0].flatten(), i[1]) for i in test_set]

In [3]:
output1 = 16
output2 = 16

MLP = nn.Sequential(
    nn.Linear(28 * 28, output1),
    nn.ReLU(),
    nn.Linear(output1, output2),
    nn.ReLU(),
    nn.Linear(output2, 10))

In [4]:
model, training_losses, training_accuracies, validation_accuracies = train_multi_model(train_data=training_set, test_data=test_set, model=MLP,
                        optim="MegaSAM", batch_size=1000, epochs=5, tracking=True)
                        

  0%|          | 0/5 [00:00<?, ?it/s]

NameError: name 'self' is not defined

In [ ]:
print(f"SAM training accuracies: {training_accuracies}")
print(f"SAM validation accuracies: {validation_accuracies}")

SAM training accuracies: [0.9355499744415283, 0.9374833106994629, 0.9383666515350342, 0.9388333559036255, 0.9392833113670349]
SAM validation accuracies: [0.9351000189781189, 0.9362000226974487, 0.9362000226974487, 0.9363999962806702, 0.9361000061035156]


In [ ]:
# be careful with comparisons, you have to restart the kernel every time to initialize a new model
from test import *

In [ ]:
model, training_losses, training_accuracies, validation_accuracies = train_multi_model(train_data=training_set, test_data=test_set, model=MLP,
                        optim="MegaSAM", batch_size=100, epochs=5, tracking=True)

[{'params': [Parameter containing:
tensor([[-0.0199, -0.0264, -0.0170,  ...,  0.0081, -0.0207, -0.0153],
        [ 0.0275,  0.0293,  0.0002,  ..., -0.0013,  0.0038,  0.0120],
        [-0.0076, -0.0163, -0.0095,  ...,  0.0137, -0.0054, -0.0256],
        ...,
        [ 0.0148, -0.0022,  0.0238,  ...,  0.0059, -0.0233, -0.0225],
        [ 0.0115,  0.0139,  0.0069,  ..., -0.0035, -0.0315,  0.0075],
        [-0.0104, -0.0081, -0.0148,  ..., -0.0255,  0.0064,  0.0324]],
       requires_grad=True), Parameter containing:
tensor([-0.2136,  0.6410,  0.4412, -0.0215,  0.0705,  0.0549,  0.5862,  0.0044,
         0.2059, -0.0072, -0.0377,  0.8167,  0.6488, -0.3296, -0.9736, -0.0623],
       requires_grad=True), Parameter containing:
tensor([[-0.2564,  0.6284, -0.1144,  0.0992,  0.0514, -0.4919, -0.1882,  0.0763,
          0.9567,  0.0837,  0.1264, -0.2194, -0.1003, -0.4149,  0.0261,  0.1435],
        [ 0.0306,  0.4215, -0.2447,  0.2158,  0.2035,  0.0803, -0.2460,  0.0249,
         -0.4432, -0.1980,

KeyboardInterrupt: 

In [ ]:
print(f"SAM training accuracies: {training_accuracies}")
print(f"SAM validation accuracies: {validation_accuracies}")

SAM training accuracies: [0.8651666641235352]
SAM validation accuracies: [0.9218999743461609]
